dist: trusty
sudo: required
# Not really suit, we just build docker
language: c
services:
  - docker      # docker still need sudo to start its service
git:
  depth: 1
  submodules: false
before_install:
install:
before_script:
script:
  - docker build -t docker-texlive . --network host
  - docker run --rm --network host -v "$TRAVIS_BUILD_DIR":"/LATEX" --workdir="/LATEX" docker-texlive make PROJNAME=main
  - docker images
after_failure:
after_failure:
before_deploy:
deploy:
  # Read more https://docs.travis-ci.com/user/deployment/releases/
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: builddir/main.pdf
  skip_cleanup: true
  on:
    tags: true
after_deploy:
after_script:
