dist: trusty
sudo: required
# Not really suit, we just build docker
language: c
services:
  - docker      # docker still need sudo to start its service
git:
  depth: 1
  submodules: false
before_install:
  - docker pull lzutao/docker-texlive
install:
before_script:
script:
  - docker images
  - docker run
      --rm
      --network host
      -v "$TRAVIS_BUILD_DIR":"/LATEX"
      --workdir="/LATEX"
      lzutao/docker-texlive bash -c "make lint PROJNAME=main"
after_failure:
before_deploy:
deploy:
  # Read more https://docs.travis-ci.com/user/deployment/releases/
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: builddir/main.pdf
  skip_cleanup: true
  on:
    tags: true
after_deploy:
after_script:
