dist: trusty
sudo: required
# Enable C++ support
language: ruby
services:
  - docker      # docker still need sudo to start its service
git:
  depth: 1
  submodules: false
before_install:
install:
before_script:
script:
  - docker build -t docker-texlive . --network host
  - docker run --rm --network host docker-texlive make main.tex
  - docker images
after_failure:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
